#!/bin/bash

echo "server-testfact"
sed -i '/'$1'/d' /home/nvergizov/git/ansible/server-testfact/sandbox_vars/structure.yml
A=$(grep $1 /home/nvergizov/git/ansible/server-testfact/sandbox_vars/users.yml -m1 -n |awk  '{print $1}' |sed 's/://')
B=$(($A+6))
sed -i ''$A','$B'd' /home/nvergizov/git/ansible/server-testfact/sandbox_vars/users.yml

echo "server-testfact2"
sed -i '/'$1'/d' /home/nvergizov/git/ansible/server-testfact2/sandbox_vars/structure.yml
A=$(grep $1 /home/nvergizov/git/ansible/server-testfact2/sandbox_vars/users.yml -m1 -n |awk  '{print $1}' |sed 's/://')
B=$(($A+6))
sed -i ''$A','$B'd' /home/nvergizov/git/ansible/server-testfact2/sandbox_vars/users.yml

echo "server-testfact3"
sed -i '/'$1'/d' /home/nvergizov/git/ansible/server-testfact3/sandbox_vars/structure.yml
A=$(grep $1 /home/nvergizov/git/ansible/server-testfact3/sandbox_vars/users.yml -m1 -n |awk  '{print $1}' |sed 's/://')
B=$(($A+6))
sed -i ''$A','$B'd' /home/nvergizov/git/ansible/server-testfact3/sandbox_vars/users.yml

echo "server-testfact4"
sed -i '/'$1'/d' /home/nvergizov/git/ansible/server-testfact4/sandbox_vars/structure.yml
A=$(grep $1 /home/nvergizov/git/ansible/server-testfact4/sandbox_vars/users.yml -m1 -n |awk  '{print $1}' |sed 's/://')
B=$(($A+6))
sed -i ''$A','$B'd' /home/nvergizov/git/ansible/server-testfact4/sandbox_vars/users.yml
